-- Resonance: Add taste cluster playlist support
-- Migration: 20250101000019_add_cluster_playlist_support
--
-- This migration adds support for taste-clustered playlists by:
-- 1. Creating user_taste_clusters table to store k-means cluster results
-- 2. Adding cluster_id foreign key to playlists table
--
-- Taste clusters are generated by k-means clustering on user listening
-- history embeddings to identify distinct taste groups. Each cluster
-- can have an associated playlist generated from centroid similarity search.

-- Create the user_taste_clusters table
CREATE TABLE user_taste_clusters (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    cluster_index SMALLINT NOT NULL,
    centroid_embedding vector(768),
    dominant_mood VARCHAR(50),
    dominant_genre VARCHAR(100),
    average_energy FLOAT,
    average_valence FLOAT,
    track_count INTEGER NOT NULL DEFAULT 0,
    cluster_name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, cluster_index)
);

-- Index for efficient user cluster lookups
CREATE INDEX idx_user_taste_clusters_user_id ON user_taste_clusters(user_id);

-- Add cluster reference to playlists table
ALTER TABLE playlists
ADD COLUMN cluster_id UUID REFERENCES user_taste_clusters(id) ON DELETE SET NULL;

-- Partial UNIQUE index for cluster playlists (required for ON CONFLICT (cluster_id) upsert)
CREATE UNIQUE INDEX idx_playlists_cluster_id ON playlists(cluster_id) WHERE cluster_id IS NOT NULL;

-- Table and column documentation
COMMENT ON TABLE user_taste_clusters IS 'K-means clusters of user listening history for taste-based playlist generation';
COMMENT ON COLUMN user_taste_clusters.user_id IS 'Reference to the user these clusters belong to';
COMMENT ON COLUMN user_taste_clusters.cluster_index IS 'Zero-based index of this cluster within the user''s clusters';
COMMENT ON COLUMN user_taste_clusters.centroid_embedding IS '768-dimensional centroid vector for similarity search against track embeddings';
COMMENT ON COLUMN user_taste_clusters.dominant_mood IS 'Most common mood label in this cluster (e.g., energetic, melancholic)';
COMMENT ON COLUMN user_taste_clusters.dominant_genre IS 'Most common genre in this cluster (e.g., electronic, rock)';
COMMENT ON COLUMN user_taste_clusters.average_energy IS 'Average energy level (0.0-1.0) of tracks in this cluster';
COMMENT ON COLUMN user_taste_clusters.average_valence IS 'Average valence/positivity (0.0-1.0) of tracks in this cluster';
COMMENT ON COLUMN user_taste_clusters.track_count IS 'Number of listening history tracks assigned to this cluster';
COMMENT ON COLUMN user_taste_clusters.cluster_name IS 'Generated descriptive name for the cluster (e.g., "High Energy Electronic")';
COMMENT ON COLUMN playlists.cluster_id IS 'Reference to taste cluster if this is a cluster-based playlist';
