# Composite action for Node.js + pnpm setup with caching
# Consolidates repeated setup steps across CI workflows
#
# NOTE: pnpm version is auto-detected from the "packageManager" field in package.json.
# Do not specify version explicitly as pnpm/action-setup@v4 will error on conflicts.

name: 'Setup Node.js and pnpm'
description: 'Sets up Node.js, pnpm, and optionally installs dependencies with caching'

inputs:
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  install-dependencies:
    description: 'Whether to run pnpm install'
    required: false
    default: 'true'
  working-directory:
    description: 'Working directory for pnpm install'
    required: false
    default: '.'
  frozen-lockfile:
    description: 'Use --frozen-lockfile flag for pnpm install'
    required: false
    default: 'true'

outputs:
  pnpm-store-path:
    description: 'Path to pnpm store directory'
    value: ${{ steps.pnpm-store.outputs.STORE_PATH }}
  cache-hit:
    description: 'Whether the pnpm cache was hit'
    value: ${{ steps.pnpm-cache.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    # pnpm version is auto-detected from package.json "packageManager" field
    - name: Setup pnpm
      uses: pnpm/action-setup@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'

    - name: Get pnpm store directory
      id: pnpm-store
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

    - name: Setup pnpm cache
      id: pnpm-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.pnpm-store.outputs.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        if [ "${{ inputs.frozen-lockfile }}" = "true" ]; then
          pnpm install --frozen-lockfile
        else
          pnpm install
        fi
