export { ChangePasswordModal } from './ChangePasswordModal'
export { ChangeEmailModal } from './ChangeEmailModal'
export { EditProfileModal } from './EditProfileModal'
export { DeleteAccountModal } from './DeleteAccountModal'
export { IntegrationsSettings } from './IntegrationsSettings'
